/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CookieTokenRefresh
 */
export interface CookieTokenRefresh {
    /**
     * WIll override cookie.
     * @type {string}
     * @memberof CookieTokenRefresh
     */
    refresh?: string;
    /**
     * 
     * @type {string}
     * @memberof CookieTokenRefresh
     */
    readonly access?: string;
}

export function CookieTokenRefreshFromJSON(json: any): CookieTokenRefresh {
    return CookieTokenRefreshFromJSONTyped(json, false);
}

export function CookieTokenRefreshFromJSONTyped(json: any, ignoreDiscriminator: boolean): CookieTokenRefresh {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'refresh': !exists(json, 'refresh') ? undefined : json['refresh'],
        'access': !exists(json, 'access') ? undefined : json['access'],
    };
}

export function CookieTokenRefreshToJSON(value?: CookieTokenRefresh | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'refresh': value.refresh,
    };
}


