name: Push to Stable Branch
on:
  workflow_run:
    workflows: ["CI/CD Workflow"]
    branches: [main]
    types: [completed]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - run: git push origin HEAD:stable -f
